stop_programs:
    description: Stop any running programs or zones.

#set_run_zone:
#  name: set the Run Zone
#  description: Setup to run a program zone.
#  target:
#  fields:
#    zone:
#      name: zone
#      description: The zone to be run.
#      required: true
#      example: "Lawn"

#run_zone:
#  name: Run Zone
#  description: Run a program zone.
#  target:
#  fields:
#    zone:
#      name: zone
#      description: The zone to be run.
#      required: true
#      example: "Lawn"